// Main Backend Server for HERE Student Support Platform
// ServiceNow Student Challenge Track 4: Self-Service Support Portal

import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { config } from './config.js';
import { initDb } from '../database/db.js';

import authRoutes from './routes/auth.js';
import chatRoutes from './routes/chat.js';
import safetyRoutes from './routes/safety.js';
import mlRoutes from './routes/ml.js';
import caseRoutes from './routes/cases.js';
import appointmentRoutes from './routes/appointments.js';
import waitlistRoutes from './routes/waitlist.js';
import resourceRoutes from './routes/resources.js';
import counsellorRoutes from './routes/counsellor.js';
import adminRoutes from './routes/admin.js';

const app = express();

// Initialize Persistent Database
initDb();

// Middlewares
app.use(cors({ origin: config.corsOrigin }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Request logging for observability
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    if (!req.path.includes('/health')) {
      console.log(`[HTTP] ${req.method} ${req.path} -> ${res.statusCode} (${duration}ms)`);
    }
  });
  next();
});

// Health Check
// Reports which conversational engine is actually live. Without this, a
// missing LLM key is indistinguishable from a working one: the request
// succeeds, the reply is just noticeably worse.
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ONLINE',
    platform: 'HERE Student Wellbeing Support Engine',
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    conversationalEngine: {
      mode: config.llm.apiKey ? `UPSTREAM_LLM (${config.llm.provider}/${config.llm.model})` : 'LOCAL_RULE_ENGINE',
      llmKeyPresent: Boolean(config.llm.apiKey),
      // Set LLM_API_KEY / LLM_PROVIDER / LLM_MODEL to enable upstream generation.
      hint: config.llm.apiKey ? null : 'LLM_API_KEY is not set — replies are generated by the offline rule-based engine.'
    }
  });
});

// Mount Routes
app.use('/api/auth', authRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/safety', safetyRoutes);
app.use('/api/ml', mlRoutes);
app.use('/api/cases', caseRoutes);
app.use('/api/appointments', appointmentRoutes);
app.use('/api/waitlist', waitlistRoutes);
app.use('/api/resources', resourceRoutes);
app.use('/api/counsellor', counsellorRoutes);
app.use('/api/admin', adminRoutes);

// Error Handling Middleware
app.use((err, req, res, next) => {
  console.error('[SERVER ERROR]', err);
  res.status(500).json({
    error: 'Internal Server Error',
    message: err.message || 'An unexpected error occurred.'
  });
});

// Exported so the dev runner (scripts/dev.js) can mount this app in the same
// process as Vite. Spawning it as a child process orphans the API on restart,
// which leaves a stale keyless server holding port 5000.
export { app };

function banner(port) {
  console.log('====================================================');
  console.log(`🚀 HERE Backend API Server running on port ${port}`);
  console.log(`🌐 API Endpoints: http://localhost:${port}/api/health`);
  console.log(`🧠 ML Model Layer: Scikit-Learn TF-IDF Pipeline`);
  if (config.llm.apiKey) {
    console.log(`🤖 Conversational Engine: UPSTREAM LLM (${config.llm.provider}/${config.llm.model})`);
  } else {
    console.log(`🤖 Conversational Engine: LOCAL RULE-BASED FALLBACK`);
    console.log(`   ↳ LLM_API_KEY is not set. Replies will read as canned.`);
    console.log(`   ↳ Add LLM_API_KEY (and optionally LLM_PROVIDER / LLM_MODEL) to the environment.`);
  }
  console.log('====================================================');
}

// Pass port 0 to let the OS assign a free port, then read it back with
// server.address().port. Returns a promise so callers can wait for the
// listener instead of guessing when it is ready.
export function startApi(port = config.port) {
  return new Promise((resolve) => {
    const server = app.listen(port, () => {
      banner(server.address().port);
      resolve(server);
    });
  });
}

// Only listen when run directly (`npm run server`), not when imported.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  startApi(config.port);
}
